---
title: "R Notebook"
output: html_notebook
---



```{r}
library("BSDA")
install.packages("fitdistrplus")
library("fitdistrplus")
```

```{r}
df <- read.csv2("whole_year_2019_blitz.csv", header=TRUE, sep=",")

ratios <- data.frame(rating = seq(1000, 2100, by=20), all=0, castling=0)
success <- data.frame(rating = seq(1000, 2100, by=20), castling=0, wins=0)

overal <- data.frame(rating = seq(1000, 2100, by=20), games=0, wins=0)
```


```{r}
for (i in ratios$rating) {
  ratios$all[ratios$rating == i] = length(df$rating[df$rating %in% seq(i, i + 20)])
  ratios$castling[ratios$rating == i] = sum(df$castling[df$rating %in% seq(i, i + 20)])
  
  overal$games[overal$rating == i] = ratios$all[ratios$rating == i]
  
  won <- df[df$rating %in% seq(i, i + 20),]
  won <- as.numeric(won$victory) == 3
  overal$wins[overal$rating == i] = sum(won)
  
  
  
  with_castling <- df[as.numeric(df$castling)==1,]
  with_castling <- with_castling[with_castling$rating %in% seq(i, i + 20),]
  
  success$castling[success$rating == i] = length(with_castling$rating)
  with_castling <- with_castling[as.numeric(with_castling$victory) == 3,]
  success$wins[success$rating == i] <- length(with_castling$rating)
}


plot(x = overal$rating, y = overal$wins / overal$games, type="l")

plot(x = success$rating, y = success$wins / success$castling, type="l")
plot(x = ratios$rating, y = ratios$castling / ratios$all, type="l")
```
```{r}
func <- success$wins / success$castling ~ success$rating
linear_model = lm(func)
summary(linear_model)

plot(func, col="blue", pch=16)
abline(linear_model, col="red")
```

```{r}
data_wins <- df$victory[as.numeric(df$victory) != 2]
length(df$victory)

data.castling_wins = df$victory[df$castling == 1]
data.castling_wins = data.castling_wins #[as.numeric(data.castling_wins) != 2]


x <- as.numeric(as.character(data_wins))
y = as.numeric(as.character(data.castling_wins))
t.test(x = x, y = y, alternative="less")
```

```{r}
data.no_castling <- df$victory[df$castling==0]
data.no_castling_wins <- data.no_castling #[as.numeric(data.no_castling) != 2]
x <- as.numeric(as.character(data_wins))
y <- as.numeric(as.character(data.no_castling_wins))
t.test(x=x, y=y, alternative="greater")
```

```{r}
castling_moves = df$move_number[df$move_number != 0]
hist(castling_moves, breaks=seq(2, 55), probability=T)

freq <- c()
for (i in seq(0, 100)) {
  freq[i] = sum(castling_moves == i) / length(castling_moves)
}
expected <- dpois(x = 0:99, lambda = mean(castling_moves))
sum(expected)

plot(freq)
plot(expected)

chisq.test(x=freq, p=expected)


y <- rpois(length(castling_moves), lambda=mean(castling_moves))

ks.test(castling_moves, y)

descdist(castling_moves)
fit.gamma <- fitdist(castling_moves, "exp")
plot(fit.gamma)
```

```{r}
mu <- mean(castling_moves)
sd = sd(castling_moves)
fit.gamma
shape <- fit.gamma$estimate[1]
rate <- fit.gamma$estimate[2]

ks.test(castling_moves, "plnorm")
```

